In [1]:
import pandas as pd

In [2]:
# Struktur und Datenqualität des Datensatzes untersuchen
# Tabellenblätter der Excel-Datei anzeigen 
excel_file = pd.ExcelFile("data/raw/real_estate_prices_2012_2025.xlsx")
excel_file.sheet_names

['Stanovi_apartmani EUR',
 'Obiteljske kuće_ EUR',
 'Građevinska zemljišta EUR',
 'Poljoprivredna zemljišta EUR',
 'Šumska zemljišta EUR',
 'Poslovni prostori EUR']

In [3]:
# Tabellenblat mit den Preisen für Wohnungen und Apartments einlesen
df_prices = pd.read_excel(
    "data/raw/real_estate_prices_2012_2025.xlsx",
    sheet_name="Stanovi_apartmani EUR"
)

df_prices.head()

# Aus der Dokumentation weiß ich dass "z" < als 10 Transaktionen und "." keine Transaktionen bedeutet - sind also keine normalen "Zahlen"

,Šifra,Naziv županije,Naziv JLS-a,Tip JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.,"""."" označava da nema transakcija"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""z"" označava da ima manje od 10 transakcija pa..."
1,19.0,Vukovarsko-srijemska,ANDRIJAŠEVCI,Općina,z,.,.,.,.,.,.,.,z,.,.,.,z,.,NaN
2,27.0,Osječko-baranjska,ANTUNOVAC,Općina,z,.,.,.,.,.,.,z,z,z,z,.,.,.,NaN
3,35.0,Vukovarsko-srijemska,BABINA GREDA,Općina,.,.,.,.,.,.,.,.,.,.,z,.,.,.,NaN
4,43.0,Primorsko-goranska,BAKAR,Grad,z,z,667.880819,z,z,z,751.446151,547.865209,979.514324,948.976124,z,1108,1542.27002,2073.72998,NaN

In [4]:
# Überblick über die den DataFrame und die Datentypen anzeigen 
df_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Šifra                             556 non-null    float64
 1   Naziv županije                    556 non-null    str
 2   Naziv JLS-a                       556 non-null    str
 3   Tip JLS-a                         556 non-null    str
 4   2012.                             556 non-null    object
 5   2013.                             556 non-null    object
 6   2014.                             556 non-null    object
 7   2015.                             556 non-null    object
 8   2016.                             556 non-null    object
 9   2017.                             556 non-null    object
 10  2018.                             556 non-null    object
 11  2019.                             556 non-null    object
 12  2020.                             556 non-null    object
 13  2021.                             556 non-null    object
 14  2022.                             556 non-null    object
 15  2023.                             556 non-null    object
 16  2024.                             556 non-null    object
 17  2025.                             556 non-null    object
 18  "." označava da nema transakcija  1 non-null      str
dtypes: float64(1), object(14), str(4)
memory usage: 82.8+ KB

In [5]:
# Anzahl der fehlenden Werte pro Spalte überprüfen 
df_prices.isna().sum()

Šifra                                 1
Naziv županije                        1
Naziv JLS-a                           1
Tip JLS-a                             1
2012.                                 1
2013.                                 1
2014.                                 1
2015.                                 1
2016.                                 1
2017.                                 1
2018.                                 1
2019.                                 1
2020.                                 1
2021.                                 1
2022.                                 1
2023.                                 1
2024.                                 1
2025.                                 1
"." označava da nema transakcija    556
dtype: int64

In [6]:
# Anzahl der doppelten Zeilen überprüfen 
df_prices.duplicated().sum()

np.int64(0)

In [7]:
# Nach der geprüften Struktur, fehlende Werte und Duplikate beginne ich mit Data Cleaning
# Letze Spalte entfernt, da es keine Analysevariable ist sondern nur eine Fußnote

df_prices = df_prices.drop(columns=df_prices.columns[-1])

In [8]:
df_prices.shape

(557, 18)

In [9]:
# Komplett leere Zeilen aus dem df entfernen 
df_prices = df_prices.dropna(how="all") # lösche eine Zeile nur dann, wenn alle Werte dieser Zeile NaN sind

df_prices.shape

(556, 18)

In [10]:
# Einzigartige Werte der Spalte 2025 überprüfen
df_prices.loc[:, "2025."].unique()

array(['.', 2073.72998046875, 'z', 3522.010009765625, 2223.330078125,
       853.6799926757812, 856.3200073242188, 795.1156616210938,
       1845.9300537109375, 2712.8798828125, 2241.7900390625,
       1624.1298828125, 3100, 1513.4100341796875, 2119.389892578125,
       3075.3076171875, 2862.297119140625, 1757.3349609375,
       1011.1199951171875, 1324.0400390625, 3024.85009765625,
       908.8599853515625, 1103.635009765625, 3920.860107421875,
       1380.9395751953125, 1713.31005859375, 2427.594970703125,
       1295.0899658203125, 1929.760009765625, 1228.6099853515625,
       1495.9100341796875, 2350.949951171875, 1507.0650634765625,
       1767.6400146484375, 1957.9100341796875, 1960.656005859375,
       1360.72998046875, 2779.97998046875, 1917.8082275390625,
       1813.1600341796875, 2601.4599609375, 2553.18994140625,
       2305.93994140625, 1107.1400146484375, 2777.27001953125,
       2651.640625, 2097.18994140625, 1773.4000244140625,
       2316.010009765625, 2444.169921875, 2231.840087890625, 1606,
       3434.972900390625, 1296.6500244140625, 2688.030029296875,
       2424.449951171875, 3614.7548828125, 1464.6199951171875,
       2778.24560546875, 3050.669921875, 3586.114990234375,
       2548.0849609375, 2273.02001953125, 1600, 2511.669921875,
       2743.93505859375, 1432.06005859375, 2770.080078125,
       2498.570068359375, 3125.719970703125, 1478.739990234375,
       744.8800048828125, 2961.35009765625, 3195.89990234375, 3830,
       1809.8299560546875, 1900.5400390625, 1850, 1666.1099853515625,
       936.1500244140625, 2418.983154296875, 2950.12255859375, 875.125,
       2184.0419921875, 2182.264892578125, 1059.7449951171875,
       1467.4547119140625, 2092.97998046875, 2057.177978515625,
       3061.030029296875, 2774.419921875, 2271.909912109375,
       2302.030029296875, 1188.9000244140625, 1944.9647216796875,
       3472.949951171875, 2261.389892578125, 2456.219970703125,
       3538.10498046875, 2422.2099609375, 2039.030029296875,
       2807.67431640625, 3032.18994140625, 3354.735107421875,
       2371.14501953125, 2175.0478515625, 1659.1300048828125, 1324.5,
       1248.43994140625, 1488.0250244140625, 2520.43994140625,
       2799.1201171875, 4067.25, 2384.739990234375, 1573.39404296875,
       2285.279052734375, 2700.27001953125, 2612.300048828125,
       2413.3798828125, 1819.9849853515625, 1815.905029296875,
       1536.31005859375, 2436.469970703125, 2497.482666015625,
       2831.3798828125, 2484.860107421875, 2272.97998046875,
       3551.1298828125, 1035.574951171875, 2127.659912109375,
       2246.6650390625, 1441.3800048828125, 2128.090087890625,
       1518.8699951171875, 2483.4052734375, 2310.5400390625,
       2331.72509765625, 714.8973388671875, 2832.219970703125,
       1953.56005859375, 1010.780029296875, 1883.812255859375,
       2874.22998046875, 2916.68505859375, 2034.8800048828125,
       2576.330078125, 3017.31005859375, 1060.780029296875], dtype=object)

In [11]:
# Sonderwerte "." und "z" in den Jahresspalten durch fehlende Werte ersetzt 

year_columns = [f"{year}." for year in range(2012,2026)]

df_prices.loc[:, year_columns] =(
    df_prices.loc[:, year_columns]
    .replace({".": pd.NA, "z": pd.NA})
)

In [12]:
df_prices.loc[:, "2025."].unique()

# Cleaning hat funktioniert, jetzt noch die object spalten ändern damit ich die später Median, Preisentwicklung, Diagramme berechne

array([<NA>, 2073.72998046875, 3522.010009765625, 2223.330078125,
       853.6799926757812, 856.3200073242188, 795.1156616210938,
       1845.9300537109375, 2712.8798828125, 2241.7900390625,
       1624.1298828125, 3100, 1513.4100341796875, 2119.389892578125,
       3075.3076171875, 2862.297119140625, 1757.3349609375,
       1011.1199951171875, 1324.0400390625, 3024.85009765625,
       908.8599853515625, 1103.635009765625, 3920.860107421875,
       1380.9395751953125, 1713.31005859375, 2427.594970703125,
       1295.0899658203125, 1929.760009765625, 1228.6099853515625,
       1495.9100341796875, 2350.949951171875, 1507.0650634765625,
       1767.6400146484375, 1957.9100341796875, 1960.656005859375,
       1360.72998046875, 2779.97998046875, 1917.8082275390625,
       1813.1600341796875, 2601.4599609375, 2553.18994140625,
       2305.93994140625, 1107.1400146484375, 2777.27001953125,
       2651.640625, 2097.18994140625, 1773.4000244140625,
       2316.010009765625, 2444.169921875, 2231.840087890625, 1606,
       3434.972900390625, 1296.6500244140625, 2688.030029296875,
       2424.449951171875, 3614.7548828125, 1464.6199951171875,
       2778.24560546875, 3050.669921875, 3586.114990234375,
       2548.0849609375, 2273.02001953125, 1600, 2511.669921875,
       2743.93505859375, 1432.06005859375, 2770.080078125,
       2498.570068359375, 3125.719970703125, 1478.739990234375,
       744.8800048828125, 2961.35009765625, 3195.89990234375, 3830,
       1809.8299560546875, 1900.5400390625, 1850, 1666.1099853515625,
       936.1500244140625, 2418.983154296875, 2950.12255859375, 875.125,
       2184.0419921875, 2182.264892578125, 1059.7449951171875,
       1467.4547119140625, 2092.97998046875, 2057.177978515625,
       3061.030029296875, 2774.419921875, 2271.909912109375,
       2302.030029296875, 1188.9000244140625, 1944.9647216796875,
       3472.949951171875, 2261.389892578125, 2456.219970703125,
       3538.10498046875, 2422.2099609375, 2039.030029296875,
       2807.67431640625, 3032.18994140625, 3354.735107421875,
       2371.14501953125, 2175.0478515625, 1659.1300048828125, 1324.5,
       1248.43994140625, 1488.0250244140625, 2520.43994140625,
       2799.1201171875, 4067.25, 2384.739990234375, 1573.39404296875,
       2285.279052734375, 2700.27001953125, 2612.300048828125,
       2413.3798828125, 1819.9849853515625, 1815.905029296875,
       1536.31005859375, 2436.469970703125, 2497.482666015625,
       2831.3798828125, 2484.860107421875, 2272.97998046875,
       3551.1298828125, 1035.574951171875, 2127.659912109375,
       2246.6650390625, 1441.3800048828125, 2128.090087890625,
       1518.8699951171875, 2483.4052734375, 2310.5400390625,
       2331.72509765625, 714.8973388671875, 2832.219970703125,
       1953.56005859375, 1010.780029296875, 1883.812255859375,
       2874.22998046875, 2916.68505859375, 2034.8800048828125,
       2576.330078125, 3017.31005859375, 1060.780029296875], dtype=object)

In [13]:
# Jahresspalten 2012 bis 2025 in numerische Datentypen umwandeln 

for col in year_columns:
    df_prices.loc[:, col] = pd. to_numeric(df_prices.loc[:, col])

df_prices.loc[:, year_columns].dtypes

2012.    object
2013.    object
2014.    object
2015.    object
2016.    object
2017.    object
2018.    object
2019.    object
2020.    object
2021.    object
2022.    object
2023.    object
2024.    object
2025.    object
dtype: object

In [14]:
for col in year_columns:
    df_prices[col] = df_prices[col].astype("Float64")
    
    df_prices.loc[:, year_columns].dtypes

In [15]:
df_prices.loc[:, year_columns].dtypes

2012.    Float64
2013.    Float64
2014.    Float64
2015.    Float64
2016.    Float64
2017.    Float64
2018.    Float64
2019.    Float64
2020.    Float64
2021.    Float64
2022.    Float64
2023.    Float64
2024.    Float64
2025.    Float64
dtype: object

In [16]:
# Anzahl der fehlenden Werte pro Spalte prüfen 

df_prices.isna().sum()

Šifra               0
Naziv županije      0
Naziv JLS-a         0
Tip JLS-a           0
2012.             428
2013.             437
2014.             432
2015.             435
2016.             413
2017.             413
2018.             400
2019.             377
2020.             387
2021.             386
2022.             364
2023.             383
2024.             393
2025.             410
dtype: int64

In [17]:
# Einzigartige Werte der Spalte "Naziv zupanije"- Gespanschaften, Einheiten prüfen 
df_prices["Naziv županije"].unique()

<StringArray>
[  'Vukovarsko-srijemska',      'Osječko-baranjska',     'Primorsko-goranska',
               'Istarska',             'Karlovačka',   'Splitsko-dalmatinska',
       'Brodsko-posavska',     'Krapinsko-zagorska',             'Zagrebačka',
            'Varaždinska',             'Međimurska',               'Zadarska',
 'Bjelovarsko-bilogorska',       'Šibensko-kninska', 'Dubrovačko-neretvanska',
      'Požeško-slavonska',          'Ličko-senjska',  'Virovitičko-podravska',
     'Sisačko-moslavačka', 'Koprivničko-križevačka',            'Grad Zagreb']
Length: 21, dtype: str

In [18]:
# Daten auf die Gespanschaft Istrien filtern
df_prices_istria =df_prices.loc[df_prices["Naziv županije"] == "Istarska"]

df_prices_istria

,Šifra,Naziv županije,Naziv JLS-a,Tip JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.
5,51.0,Istarska,BALE - VALLE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4264.0,<NA>,<NA>
6,60.0,Istarska,BARBAN,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
43,400.0,Istarska,BRTONIGLA - VERTENEGLIO,Općina,1347.442047,<NA>,<NA>,1071.493762,1007.84885,1263.790684,1185.710631,1247.057985,<NA>,1305.227233,1639.108149,<NA>,3265.570068,<NA>
45,426.0,Istarska,BUJE - BUIE,Grad,1162.6586,1075.72567,957.842279,1009.878179,876.134871,773.275152,1033.225723,989.219498,998.722961,1139.83669,1313.207293,1229.0,1947.280884,2119.389893
47,434.0,Istarska,BUZET,Grad,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,782.457661,<NA>,881.52136,895.991784,<NA>,<NA>,<NA>
50,477.0,Istarska,CEROVLJE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
114,6190.0,Istarska,FAŽANA - FASANA,Općina,1162.70915,1230.736241,1336.776053,1101.610978,1221.119978,1137.523631,1226.410049,1308.469967,1709.675208,1667.725321,1824.440127,2102.0,2898.419922,<NA>
117,6297.0,Istarska,FUNTANA - FONTANE,Općina,<NA>,<NA>,1056.97447,1318.101961,1265.267021,1428.050615,1567.908869,1625.002013,1620.541654,1946.809426,1526.147689,2228.0,<NA>,<NA>
135,1325.0,Istarska,GRAČIŠĆE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
140,1384.0,Istarska,GROŽNJAN - GRISIGNANA,Grad,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
176,1759.0,Istarska,KANFANAR,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1889.0,<NA>,<NA>
181,5967.0,Istarska,KAROJBA,Grad,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
184,5975.0,Istarska,KAŠTELIR-LABINCI - CASTELLIERE-S. DOMENICA,Općina,<NA>,<NA>,1212.950592,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1255.0,<NA>,<NA>
219,2178.0,Istarska,KRŠAN,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1019.153884,1915.0,<NA>,<NA>
225,2224.0,Istarska,LABIN,Općina,929.908718,893.70002,888.767701,915.887048,925.154159,896.660206,971.885897,981.168949,1178.479464,1171.720602,1166.362078,1398.0,2033.569946,2688.030029
226,2232.0,Istarska,LANIŠĆE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
237,2356.0,Istarska,LIŽNJAN - LISIGNANO,Općina,1038.244911,974.659433,929.743379,763.86528,834.865885,1010.284021,1067.078702,1147.084614,1005.506388,1258.644232,1451.679566,1916.0,2185.550049,2424.449951
250,2461.0,Istarska,LUPOGLAV,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
260,2542.0,Istarska,MARČANA,Općina,<NA>,1101.032832,<NA>,<NA>,868.111637,1118.812106,993.494686,1140.958314,1129.254521,1234.718773,1595.379224,1928.0,2332.439941,<NA>
269,2631.0,Istarska,MEDULIN,Općina,1207.423104,1205.752575,1137.781661,1124.178521,1189.183762,1206.392618,1259.599373,1252.190941,1237.994955,1468.232757,1444.036728,2152.0,2085.719971,2273.02002
277,2747.0,Istarska,MOTOVUN - MONTONA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
298,2917.0,Istarska,NOVIGRAD - CITTANOVA,Općina,1530.521434,1492.556725,1586.184508,1301.486109,1227.706175,<NA>,<NA>,<NA>,1584.574252,1648.88347,2012.227737,2302.0,<NA>,<NA>
311,3042.0,Istarska,OPRTALJ - PORTOLE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
328,3212.0,Istarska,PAZIN,Veliki grad,980.962016,768.881375,746.610688,743.540299,734.223508,714.489103,785.774562,894.030537,792.723548,948.63919,986.272457,1428.0,1445.515015,2182.264893
336,3301.0,Istarska,PIĆAN,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
358,3484.0,Istarska,POREČ - PARENZO,Grad,1329.078504,1214.529174,1302.57166,1262.39339,1291.302355,1352.933544,1409.602607,1489.554113,1565.859531,1756.856546,1978.912368,2235.0,2731.330078,2774.419922
376,3590.0,Istarska,PULA - POLA,Veliki grad,1035.009059,941.401573,908.296499,909.205358,966.719318,988.352043,1007.531475,1153.703963,1133.97381,1192.064251,1408.01778,1911.0,2166.998779,2456.219971
385,3689.0,Istarska,RAŠA,Općina,1063.053554,<NA>,952.691568,<NA>,680.73639,626.459457,1064.868034,469.724224,457.318921,876.828094,843.393761,<NA>,1736.029663,2039.030029
392,3743.0,Istarska,ROVINJ - ROVIGNO,Grad,1675.407125,1644.979341,1520.782924,1748.251978,1574.260467,1725.835481,1718.247848,1915.392429,2012.049479,2265.303827,2690.436751,3000.0,3500.0,3354.735107
444,4324.0,Istarska,SVETA NEDELJA,Grad,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,942.057162,<NA>,1825.650024,2413.379883
453,4316.0,Istarska,SVETI LOVREČ,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2000.0,<NA>,<NA>
456,4332.0,Istarska,SVETI PETAR U ŠUMI,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
457,4359.0,Istarska,SVETVINČENAT,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
469,6319.0,Istarska,TAR-VABRIGA - TORRE-ABREGA,Općina,1275.18311,1208.560374,1391.479754,1053.748416,1136.910554,1344.859994,1266.046644,1421.175552,1411.569999,1678.068403,1694.555695,1982.0,2079.48999,2831.379883
470,4537.0,Istarska,TINJAN,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
488,4685.0,Istarska,UMAG - UMAGO,Grad,1540.61543,1128.416959,1413.260841,1300.796192,1290.014069,1161.800833,1426.525705,1519.869603,1708.133959,1862.277953,1931.430005,2676.0,2640.870117,3551.129883
516,4979.0,Istarska,VIŠNJAN - VISIGNANO,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1774.0,<NA>,<NA>
517,4987.0,Istarska,VIŽINADA - VISINADA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
521,5029.0,Istarska,VODNJAN - DIGNANO,Grad,995.773771,947.930877,888.371896,960.28228,950.821601,999.908838,1003.339459,1008.820945,1014.575696,1215.807744,1487.23865,<NA>,2085.75,2331.725098
534,5169.0,Istarska,VRSAR - ORSERA,Općina,1236.981432,1276.581993,1556.702255,<NA>,1150.625489,1236.790402,1807.100007,1536.708498,1837.269723,1594.218975,1845.492635,2175.0,2885.679932,2832.219971
553,5312.0,Istarska,ŽMINJ,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,883.90338,<NA>,<NA>,2576.330078

In [19]:
# Anzahl der Zeilen und Spalten des Istriens-Datensatzes 
df_prices_istria.shape

# offiziele Preisdatensätze 41 (Städte/Gemeinden) für die Gespanschaft Istrien

(41, 18)

In [20]:
# Name der Städte und Gemeinden in Istrien anzeigen 
df_prices_istria["Naziv JLS-a"].unique()

<StringArray>
[                              'BALE - VALLE',
                                     'BARBAN',
                    'BRTONIGLA - VERTENEGLIO',
                                'BUJE - BUIE',
                                      'BUZET',
                                   'CEROVLJE',
                            'FAŽANA - FASANA',
                          'FUNTANA - FONTANE',
                                   'GRAČIŠĆE',
                      'GROŽNJAN - GRISIGNANA',
                                   'KANFANAR',
                                    'KAROJBA',
 'KAŠTELIR-LABINCI - CASTELLIERE-S. DOMENICA',
                                      'KRŠAN',
                                      'LABIN',
                                    'LANIŠĆE',
                        'LIŽNJAN - LISIGNANO',
                                   'LUPOGLAV',
                                    'MARČANA',
                                    'MEDULIN',
                          'MOTOVUN - MONTONA',
                       'NOVIGRAD - CITTANOVA',
                          'OPRTALJ - PORTOLE',
                                      'PAZIN',
                                      'PIĆAN',
                            'POREČ - PARENZO',
                                'PULA - POLA',
                                       'RAŠA',
                           'ROVINJ - ROVIGNO',
                              'SVETA NEDELJA',
                               'SVETI LOVREČ',
                         'SVETI PETAR U ŠUMI',
                               'SVETVINČENAT',
                 'TAR-VABRIGA - TORRE-ABREGA',
                                     'TINJAN',
                               'UMAG - UMAGO',
                        'VIŠNJAN - VISIGNANO',
                        'VIŽINADA - VISINADA',
                          'VODNJAN - DIGNANO',
                             'VRSAR - ORSERA',
                                      'ŽMINJ']
Length: 41, dtype: str

In [21]:
# Anzahl der fehlenden Werten im Istrien-Datensatz überprüfen 
df_prices_istria.isna().sum()

Šifra              0
Naziv županije     0
Naziv JLS-a        0
Tip JLS-a          0
2012.             25
2013.             26
2014.             24
2015.             26
2016.             23
2017.             24
2018.             24
2019.             23
2020.             24
2021.             22
2022.             19
2023.             20
2024.             24
2025.             26
dtype: int64

In [22]:
df_prices_istria.duplicated().sum()

np.int64(0)

In [23]:
# Tabellenblätter der Excel-Datei mit den Immobilientransaktionen anzeigen 
pd.ExcelFile("data/raw/real_estate_transactions_2012_2025.xlsx").sheet_names

['Kupoprodaje',
 'Stanovi i apartmani',
 'Obiteljske kuće',
 'Građevinska zemljišta',
 'Poljoprivredna zemljišta',
 'Šumska zemljišta',
 'Poslovni prostori']

In [24]:
# Transaktionsdaten für Wohnungen und Apartments einlesen 
df_transactions = pd.read_excel(
    "data/raw/real_estate_transactions_2012_2025.xlsx",
    sheet_name="Stanovi i apartmani"
)

df_transactions.head()

,Šifra,Naziv županije,Naziv JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.,"""z"" označava manje od 10 transakcija"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""."" označava da nema transakcija"
1,19.0,Vukovarsko-srijemska,ANDRIJAŠEVCI,z,.,.,.,.,.,.,.,z,.,.,.,z,.,NaN
2,27.0,Osječko-baranjska,ANTUNOVAC,z,.,.,.,.,.,.,z,z,z,z,.,.,.,NaN
3,35.0,Vukovarsko-srijemska,BABINA GREDA,.,.,.,.,.,.,.,.,.,.,z,.,.,.,NaN
4,43.0,Primorsko-goranska,BAKAR,z,z,11,11,z,z,10,10,11,11,z,16,27,21,NaN

In [25]:
# Überblick über den df und die Datentypen 
df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Šifra                                 556 non-null    float64
 1   Naziv županije                        556 non-null    str
 2   Naziv JLS-a                           556 non-null    str
 3   2012.                                 556 non-null    object
 4   2013.                                 556 non-null    object
 5   2014.                                 556 non-null    object
 6   2015.                                 556 non-null    object
 7   2016.                                 556 non-null    object
 8   2017.                                 556 non-null    object
 9   2018.                                 556 non-null    object
 10  2019.                                 556 non-null    object
 11  2020.                                 556 non-null    object
 12  2021.                                 556 non-null    object
 13  2022.                                 556 non-null    object
 14  2023.                                 556 non-null    object
 15  2024.                                 556 non-null    object
 16  2025.                                 556 non-null    object
 17  "z" označava manje od 10 transakcija  1 non-null      str
dtypes: float64(1), object(14), str(3)
memory usage: 78.5+ KB

In [26]:
# Erste Zeile mit den Erklärungen entfernen
df_transactions = df_transactions.drop(index=0).reset_index(drop=True)

df_transactions.shape

(556, 18)

In [27]:
# Letzte Fußnotenspalte entfernen
df_transactions = df_transactions.drop(columns=df_transactions.columns[-1])

df_transactions.shape

(556, 17)

In [28]:
# Einzigartige Werte der Spalte 2025 überprüfen 
df_transactions.loc[:, "2025."].unique()

array(['.', 21, 'z', 19, 24, 17, 23, 26, 11, 44, 18, 133, 49, 16, 30, 215,
       172, 13, 71, 12, 10, 142, 22, 130, 14, 64, 29, 7616, 25, 260, 77,
       117, 48, 59, 129, 55, 110, 57, 66, 27, 54, 51, 111, 60, 126, 34,
       119, 46, 40, 69, 179, 96, 94, 15, 41, 98, 670, 52, 20, 68, 212, 89,
       388, 1136, 50, 140, 114, 43, 87, 820, 31, 80, 58, 182, 225, 167,
       404, 152, 177, 72, 136, 131, 135, 707, 365], dtype=object)

In [29]:
# Spaltennamen des Transaktionsdatensatzes prüfen

df_transactions.columns

Index(['Šifra', 'Naziv županije', 'Naziv JLS-a', '2012.', '2013.', '2014.',
       '2015.', '2016.', '2017.', '2018.', '2019. ', '2020. ', '2021.',
       '2022.', '2023.', '2024.', '2025.'],
      dtype='str')

In [30]:
# Leerzeichen am Anfang und Ende der Spaltennamen entfernen
df_transactions.columns = df_transactions.columns.str.strip()

df_transactions.columns

Index(['Šifra', 'Naziv županije', 'Naziv JLS-a', '2012.', '2013.', '2014.',
       '2015.', '2016.', '2017.', '2018.', '2019.', '2020.', '2021.', '2022.',
       '2023.', '2024.', '2025.'],
      dtype='str')

In [31]:
# Sonderwerte "." und "z" in den Jahresspalten durch fehlende Werte ersetzt 

year_columns = [f"{year}." for year in range(2012, 2026)]

df_transactions.loc[:, year_columns] = (
    df_transactions.loc[:, year_columns]
    .replace({"." : pd.NA, "z" : pd.NA})
)

In [32]:
df_transactions["2025."].unique()

array([<NA>, 21, 19, 24, 17, 23, 26, 11, 44, 18, 133, 49, 16, 30, 215,
       172, 13, 71, 12, 10, 142, 22, 130, 14, 64, 29, 7616, 25, 260, 77,
       117, 48, 59, 129, 55, 110, 57, 66, 27, 54, 51, 111, 60, 126, 34,
       119, 46, 40, 69, 179, 96, 94, 15, 41, 98, 670, 52, 20, 68, 212, 89,
       388, 1136, 50, 140, 114, 43, 87, 820, 31, 80, 58, 182, 225, 167,
       404, 152, 177, 72, 136, 131, 135, 707, 365], dtype=object)

In [33]:
#Datentypen der Jaresspalte in Float64 umwandeln 
for col in year_columns:
    df_transactions[col] = df_transactions[col].astype("Float64")

# Datentypen der Jahresspalte überprüfen 
df_transactions.loc[:, year_columns].dtypes

2012.    Float64
2013.    Float64
2014.    Float64
2015.    Float64
2016.    Float64
2017.    Float64
2018.    Float64
2019.    Float64
2020.    Float64
2021.    Float64
2022.    Float64
2023.    Float64
2024.    Float64
2025.    Float64
dtype: object

In [34]:
# Anzahl fehlende Werte pro Spalte 
df_transactions.isna().sum()

Šifra               0
Naziv županije      0
Naziv JLS-a         0
2012.             429
2013.             438
2014.             433
2015.             433
2016.             411
2017.             413
2018.             400
2019.             377
2020.             387
2021.             386
2022.             364
2023.             383
2024.             393
2025.             410
dtype: int64

In [35]:
# Transaktionsdaten auf die Gespanschaft Istrien filtern 
df_transactions_istria = df_transactions.loc[
    df_transactions["Naziv županije"] == "Istarska"
]

df_transactions_istria.shape

(41, 17)

In [36]:
# Anzahl der Duplikate im Istien-Transaktionsdatensatz prüfen 
df_transactions_istria.duplicated().sum()

np.int64(0)

In [37]:
# Ortsnamen der Preise- und Transaktionsdaten vergleichen 
price_jls = df_prices_istria["Naziv JLS-a"].unique()
transactions_jls = df_transactions_istria["Naziv JLS-a"].unique()

print(len(price_jls))
print(len(transactions_jls))

set(price_jls) == set(transactions_jls)

41
41

True

In [38]:
# Anzahl der fehlende Werte im Istrien-Transaktionsdatensatz überprüfen
df_transactions_istria.isna().sum()

Šifra              0
Naziv županije     0
Naziv JLS-a        0
2012.             26
2013.             27
2014.             25
2015.             27
2016.             24
2017.             24
2018.             24
2019.             23
2020.             24
2021.             22
2022.             19
2023.             19
2024.             24
2025.             26
dtype: int64

In [39]:
# Überblich über den bereinigten Transaktionsdatensatz 
df_transactions_istria.info()

# 41 Zeilen und 17 Spalten 
# "Naziv zupanije" und "Naziv JLS-a" vollständig
# 14 Jahresspalten (2012-2025) als Float64
#Sonderwerte . und z wurden als NA behandelt 
# keine duplikate

<class 'pandas.DataFrame'>
Index: 41 entries, 4 to 552
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Šifra           41 non-null     float64
 1   Naziv županije  41 non-null     str
 2   Naziv JLS-a     41 non-null     str
 3   2012.           15 non-null     Float64
 4   2013.           14 non-null     Float64
 5   2014.           16 non-null     Float64
 6   2015.           14 non-null     Float64
 7   2016.           17 non-null     Float64
 8   2017.           17 non-null     Float64
 9   2018.           17 non-null     Float64
 10  2019.           18 non-null     Float64
 11  2020.           17 non-null     Float64
 12  2021.           19 non-null     Float64
 13  2022.           22 non-null     Float64
 14  2023.           22 non-null     Float64
 15  2024.           17 non-null     Float64
 16  2025.           15 non-null     Float64
dtypes: Float64(14), float64(1), str(2)
memory usage: 6.3 KB

In [40]:
# Bereinigte Immobilienpreisdaten spiechern 
df_prices_istria.to_csv(
    "data/processed/real_price_istria_clean.csv",
    index=False
)

# Bereinigte Transaktionsdaten speichern 
df_transactions_istria.to_csv(
    "data/processed/real_estate_transactions_istria_clean.csv",
    index=False
)

In [41]:
# Bereinigte Transaktionsdaten speichern 
df_transactions_istria.to_csv(
    "data/processed/real_estate_prices_istria_clean.csv",
    index=False
)

In [42]:
import pandas as pd

In [43]:
# Tourismusdaten Deutschland - Istrien einlesen 
df_tourism_germany = pd.read_csv(
    "data/raw/tourism_germany_istria_2019_2025.csv"
)

df_tourism_germany.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Table 1.3. Tourist arrivals and nights, by country of residence, Republic of Croatia, counties, by months
Spatial unit     Countries 2019 01 Tourist arrivals 2019 01 Tourist nights 2019 02 Tourist arrivals 2019 02 Tourist nights 2019 03 Tourist arrivals 2019 03 Tourist nights 2019 04 Tourist arrivals 2019 04 Tourist nights 2019 05 Tourist arrivals 2019 05 Tourist nights 2019 06 Tourist arrivals 2019 06 Tourist nights 2019 07 Tourist arrivals 2019 07 Tourist nights 2019 08 Tourist arrivals 2019 08 Tourist nights 2019 09 Tourist arrivals 2019 09 Tourist nights 2019 10 Tourist arrivals 2019 10 Tourist nights 2019 11 Tourist arrivals 2019 11 Tourist nights 2019 12 Tourist arrivals 2019 12 Tourist nights 2019 01.-12. Tourist arrivals 2019 01.-12. Tourist nights 2020 01 Tourist arrivals 2020 01 Tourist nights 2020 02 Tourist arrivals 2020 02 Tourist nights 2020 03 Tourist arrivals 2020 03 Tourist nights 2020 04 Tourist arrivals 2020 04 Tourist nights 2020 05 Tourist arrivals 2020 05 Tourist nights 2020 06 Tourist arrivals 2020 06 Tourist nights 2020 07 Tourist arrivals 2020 07 Tourist nights 2020 08 Tourist arrivals 2020 08 Tourist nights 2020 09 Tourist arrivals 2020 09 Tourist nights 2020 10 Tourist arrivals 2020 10 Tourist nights 2020 11 Tourist arrivals 2020 11 Tourist nights 2020 12 Tourist arrivals 2020 12 Tourist nights 2020 01.-12. Tourist arrivals 2020 01.-12. Tourist nights 2021 01 Tourist arrivals 2021 01 Tourist nights 2021 02 Tourist arrivals 2021 02 Tourist nights 2021 03 Tourist arrivals 2021 03 Tourist nights 2021 04 Tourist arrivals 2021 04 Tourist nights 2021 05 Tourist arrivals 2021 05 Tourist nights 2021 06 Tourist arrivals 2021 06 Tourist nights 2021 07 Tourist arrivals 2021 07 Tourist nights 2021 08 Tourist arrivals 2021 08 Tourist nights 2021 09 Tourist arrivals 2021 09 Tourist nights 2021 10 Tourist arrivals 2021 10 Tourist nights 2021 11 Tourist arrivals 2021 11 Tourist nights 2021 12 Tourist arrivals 2021 12 Tourist nights 2021 01.-12. Tourist arrivals 2021 01.-12. Tourist nights 2022 01 Tourist arrivals 2022 01 Tourist nights 2022 02 Tourist arrivals 2022 02 Tourist nights 2022 03 Tourist arrivals 2022 03 Tourist nights 2022 04 Tourist arrivals 2022 04 Tourist nights 2022 05 Tourist arrivals 2022 05 Tourist nights 2022 06 Tourist arrivals 2022 06 Tourist nights 2022 07 Tourist arrivals 2022 07 Tourist nights 2022 08 Tourist arrivals 2022 08 Tourist nights 2022 09 Tourist arrivals 2022 09 Tourist nights 2022 10 Tourist arrivals 2022 10 Tourist nights 2022 11 Tourist arrivals 2022 11 Tourist nights 2022 12 Tourist arrivals 2022 12 Tourist nights 2022 01.-12. Tourist arrivals 2022 01.-12. Tourist nights 2023 01 Tourist arrivals 2023 01 Tourist nights 2023 02 Tourist arrivals 2023 02 Tourist nights 2023 03 Tourist arrivals 2023 03 Tourist nights 2023 04 Tourist arrivals 2023 04 Tourist nights 2023 05 Tourist arrivals 2023 05 Tourist nights 2023 06 Tourist arrivals 2023 06 Tourist nights 2023 07 Tourist arrivals 2023 07 Tourist nights 2023 08 Tourist arrivals 2023 08 Tourist nights 2023 09 Tourist arrivals 2023 09 Tourist nights 2023 10 Tourist arrivals 2023 10 Tourist nights 2023 11 Tourist arrivals 2023 11 Tourist nights 2023 12 Tourist arrivals 2023 12 Tourist nights 2023 01.-12. Tourist arrivals 2023 01.-12. Tourist nights 2024 01 Tourist arrivals 2024 01 Tourist nights 2024 02 Tourist arrivals 2024 02 Tourist nights 2024 03 Tourist arrivals 2024 03 Tourist nights 2024 04 Tourist arrivals 2024 04 Tourist nights 2024 05 Tourist arrivals 2024 05 Tourist nights 2024 06 Tourist arrivals 2024 06 Tourist nights 2024 07 Tourist arrivals 2024 07 Tourist nights 2024 08 Tourist arrivals 2024 08 Tourist nights 2024 09 Tourist arrivals 2024 09 Tourist nights 2024 10 Tourist arrivals 2024 10 Tourist nights 2024 11 Tourist arrivals 2024 11 Tourist nights 2024 12 Tourist arrivals 2024 12 Tourist nights 2024 01.-12. Tourist arrivals 2024 01.-12. Tourist nights 2025 01 Tourist arrivals 2025 01 Tourist nights 2025 02 Tourist arrivals 2025 02 Tourist nights 2025 03 Tourist arrivals 2025 03 Tourist nights 2025 04 Tourist arrivals 2025 04 Tourist nights 2025 05 Tourist arrivals 2025 05 Tourist nights 2025 06 Tourist arrivals 2025 06 Tourist nights 2025 07 Tourist arrivals 2025 07 Tourist nights 2025 08 Tourist arrivals 2025 08 Tourist nights 2025 09 Tourist arrivals 2025 09 Tourist nights 2025 10 Tourist arrivals 2025 10 Tourist nights 2025 11 Tourist arrivals 2025 11 Tourist nights 2025 12 Tourist arrivals 2025 12 Tourist nights 2025 01.-12. Tourist arrivals                        2025 01.-12. Tourist nights
County of Istria Germany   478                      5512                   1445                     4951                   10138                    40996                  44181                    214843                 65858                    396073                 216539                   1682925                222187                   2012207                306740                   2635798                142706                   1339972                36123                    226441                 1594                     7189                   3654                     13287                  1051643                       8580194                     954                      7106                   2993                     11161                  2458                     8580                   4                        464                    4284                     11501                  79255                    510498                 195317                   1681314                245421                   2155473                55033                    659341                 7902                     63964                  565                      4555                   189                      2526                   594375                        5116483                     175                      2457                   328                      2357                   8140                     32191                  10718                    69215                  52829                    305540                 100560                   797650                 260815                   1920421                473085                   3946504                200793                   2001759                33250                    225839                 2274                     16836                  2105                     11740                  1145072                       9332509                     1224                     10962                  2636                     12540                  6074                     31403                  39652                    205142                 77548                    460042                 271004                   2141956                271753                   2258456                404261                   3602309                193273                   1884935                36609                    233737                 2569                     17058                  2776                     12470                  1309379                       10871010                    1248                     9415                   3203                     13286                  8042                     33475                  42233                    212878                 159403                   826499                 201704                   1885373                268739                   2182854                368432                   3263376                188866                   1723908                38208                    279158                 1835                     12939                  3818                     16504                  1285731                       10459665                    1162                     9963                   4090                     14927                  21745                    88574                  25009                    134204                 167728                   1140376                161874                   1254706                252304                   2139236                380869                   3222292                164418                   1556956                45441                    322012                 2362                     14996                  4167                     18101                  1231169                       9916343                     1156                     10089                  2722                     11298                  7752                     32443                  46607                    234238                 77310                    450783                 250965                   1960007                236918                   2046228                371886                   3059481                185293                   1814592                44358                    303032                 3565                     18229                  5017                     22210                  1233549                                                                  9962630

In [44]:
# Anzahl der Zeilen und Spalten 
df_tourism_germany.shape

(2, 1)

In [45]:
# Spaltennamen der Datensatzes prüfen 
df_tourism_germany.columns

Index(['Table 1.3. Tourist arrivals and nights, by country of residence, Republic of Croatia, counties, by months'], dtype='str')

In [46]:
# Tourismusdaten korrekt einlesen
df_tourism_germany = pd.read_csv(
    "data/raw/tourism_germany_istria_2019_2025.csv",
    skiprows=2
)

df_tourism_germany.head()

,Spatial unit,Countries,2019 01 Tourist arrivals,2019 01 Tourist nights,2019 02 Tourist arrivals,2019 02 Tourist nights,2019 03 Tourist arrivals,2019 03 Tourist nights,2019 04 Tourist arrivals,2019 04 Tourist nights,...,2025 09 Tourist arrivals,2025 09 Tourist nights,2025 10 Tourist arrivals,2025 10 Tourist nights,2025 11 Tourist arrivals,2025 11 Tourist nights,2025 12 Tourist arrivals,2025 12 Tourist nights,2025 01.-12. Tourist arrivals,2025 01.-12. Tourist nights
0,County of Istria,Germany,478,5512,1445,4951,10138,40996,44181,214843,...,185293,1814592,44358,303032,3565,18229,5017,22210,1233549,9962630

In [47]:
# Datentypen und Struktur des Datensatzes prüfen 
df_tourism_germany.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 184 entries, Spatial unit to 2025 01.-12. Tourist nights
dtypes: int64(182), str(2)
memory usage: 1.6 KB

In [48]:
# Fehlende Werte prüfen
df_tourism_germany.isna().sum()

Spatial unit                     0
Countries                        0
2019 01 Tourist arrivals         0
2019 01 Tourist nights           0
2019 02 Tourist arrivals         0
                                ..
2025 11 Tourist nights           0
2025 12 Tourist arrivals         0
2025 12 Tourist nights           0
2025 01.-12. Tourist arrivals    0
2025 01.-12. Tourist nights      0
Length: 184, dtype: int64

In [49]:
# Duplikate prüfen 
df_tourism_germany.duplicated().sum()

np.int64(0)

In [50]:
# Spaltennamen des Datensatzes prüfen 
df_tourism_germany.columns.tolist()

['Spatial unit',
 'Countries',
 '2019 01 Tourist arrivals',
 '2019 01 Tourist nights',
 '2019 02 Tourist arrivals',
 '2019 02 Tourist nights',
 '2019 03 Tourist arrivals',
 '2019 03 Tourist nights',
 '2019 04 Tourist arrivals',
 '2019 04 Tourist nights',
 '2019 05 Tourist arrivals',
 '2019 05 Tourist nights',
 '2019 06 Tourist arrivals',
 '2019 06 Tourist nights',
 '2019 07 Tourist arrivals',
 '2019 07 Tourist nights',
 '2019 08 Tourist arrivals',
 '2019 08 Tourist nights',
 '2019 09 Tourist arrivals',
 '2019 09 Tourist nights',
 '2019 10 Tourist arrivals',
 '2019 10 Tourist nights',
 '2019 11 Tourist arrivals',
 '2019 11 Tourist nights',
 '2019 12 Tourist arrivals',
 '2019 12 Tourist nights',
 '2019 01.-12. Tourist arrivals',
 '2019 01.-12. Tourist nights',
 '2020 01 Tourist arrivals',
 '2020 01 Tourist nights',
 '2020 02 Tourist arrivals',
 '2020 02 Tourist nights',
 '2020 03 Tourist arrivals',
 '2020 03 Tourist nights',
 '2020 04 Tourist arrivals',
 '2020 04 Tourist nights',
 '2020 05 Tourist arrivals',
 '2020 05 Tourist nights',
 '2020 06 Tourist arrivals',
 '2020 06 Tourist nights',
 '2020 07 Tourist arrivals',
 '2020 07 Tourist nights',
 '2020 08 Tourist arrivals',
 '2020 08 Tourist nights',
 '2020 09 Tourist arrivals',
 '2020 09 Tourist nights',
 '2020 10 Tourist arrivals',
 '2020 10 Tourist nights',
 '2020 11 Tourist arrivals',
 '2020 11 Tourist nights',
 '2020 12 Tourist arrivals',
 '2020 12 Tourist nights',
 '2020 01.-12. Tourist arrivals',
 '2020 01.-12. Tourist nights',
 '2021 01 Tourist arrivals',
 '2021 01 Tourist nights',
 '2021 02 Tourist arrivals',
 '2021 02 Tourist nights',
 '2021 03 Tourist arrivals',
 '2021 03 Tourist nights',
 '2021 04 Tourist arrivals',
 '2021 04 Tourist nights',
 '2021 05 Tourist arrivals',
 '2021 05 Tourist nights',
 '2021 06 Tourist arrivals',
 '2021 06 Tourist nights',
 '2021 07 Tourist arrivals',
 '2021 07 Tourist nights',
 '2021 08 Tourist arrivals',
 '2021 08 Tourist nights',
 '2021 09 Tourist arrivals',
 '2021 09 Tourist nights',
 '2021 10 Tourist arrivals',
 '2021 10 Tourist nights',
 '2021 11 Tourist arrivals',
 '2021 11 Tourist nights',
 '2021 12 Tourist arrivals',
 '2021 12 Tourist nights',
 '2021 01.-12. Tourist arrivals',
 '2021 01.-12. Tourist nights',
 '2022 01 Tourist arrivals',
 '2022 01 Tourist nights',
 '2022 02 Tourist arrivals',
 '2022 02 Tourist nights',
 '2022 03 Tourist arrivals',
 '2022 03 Tourist nights',
 '2022 04 Tourist arrivals',
 '2022 04 Tourist nights',
 '2022 05 Tourist arrivals',
 '2022 05 Tourist nights',
 '2022 06 Tourist arrivals',
 '2022 06 Tourist nights',
 '2022 07 Tourist arrivals',
 '2022 07 Tourist nights',
 '2022 08 Tourist arrivals',
 '2022 08 Tourist nights',
 '2022 09 Tourist arrivals',
 '2022 09 Tourist nights',
 '2022 10 Tourist arrivals',
 '2022 10 Tourist nights',
 '2022 11 Tourist arrivals',
 '2022 11 Tourist nights',
 '2022 12 Tourist arrivals',
 '2022 12 Tourist nights',
 '2022 01.-12. Tourist arrivals',
 '2022 01.-12. Tourist nights',
 '2023 01 Tourist arrivals',
 '2023 01 Tourist nights',
 '2023 02 Tourist arrivals',
 '2023 02 Tourist nights',
 '2023 03 Tourist arrivals',
 '2023 03 Tourist nights',
 '2023 04 Tourist arrivals',
 '2023 04 Tourist nights',
 '2023 05 Tourist arrivals',
 '2023 05 Tourist nights',
 '2023 06 Tourist arrivals',
 '2023 06 Tourist nights',
 '2023 07 Tourist arrivals',
 '2023 07 Tourist nights',
 '2023 08 Tourist arrivals',
 '2023 08 Tourist nights',
 '2023 09 Tourist arrivals',
 '2023 09 Tourist nights',
 '2023 10 Tourist arrivals',
 '2023 10 Tourist nights',
 '2023 11 Tourist arrivals',
 '2023 11 Tourist nights',
 '2023 12 Tourist arrivals',
 '2023 12 Tourist nights',
 '2023 01.-12. Tourist arrivals',
 '2023 01.-12. Tourist nights',
 '2024 01 Tourist arrivals',
 '2024 01 Tourist nights',
 '2024 02 Tourist arrivals',
 '2024 02 Tourist nights',
 '2024 03 Tourist arrivals',
 '2024 03 Tourist nights',
 '2024 04 Tourist arrivals',
 '2024 04 Tourist nights',
 '2024 05 Tourist arrivals',
 '2024 05 Tourist nights',
 '2024 06 Tourist arrivals',
 '2024 06 Tourist nights',
 '2024 07 Tourist arrivals',
 '2024 07 Tourist nights',
 '2024 08 Tourist arrivals',
 '2024 08 Tourist nights',
 '2024 09 Tourist arrivals',
 '2024 09 Tourist nights',
 '2024 10 Tourist arrivals',
 '2024 10 Tourist nights',
 '2024 11 Tourist arrivals',
 '2024 11 Tourist nights',
 '2024 12 Tourist arrivals',
 '2024 12 Tourist nights',
 '2024 01.-12. Tourist arrivals',
 '2024 01.-12. Tourist nights',
 '2025 01 Tourist arrivals',
 '2025 01 Tourist nights',
 '2025 02 Tourist arrivals',
 '2025 02 Tourist nights',
 '2025 03 Tourist arrivals',
 '2025 03 Tourist nights',
 '2025 04 Tourist arrivals',
 '2025 04 Tourist nights',
 '2025 05 Tourist arrivals',
 '2025 05 Tourist nights',
 '2025 06 Tourist arrivals',
 '2025 06 Tourist nights',
 '2025 07 Tourist arrivals',
 '2025 07 Tourist nights',
 '2025 08 Tourist arrivals',
 '2025 08 Tourist nights',
 '2025 09 Tourist arrivals',
 '2025 09 Tourist nights',
 '2025 10 Tourist arrivals',
 '2025 10 Tourist nights',
 '2025 11 Tourist arrivals',
 '2025 11 Tourist nights',
 '2025 12 Tourist arrivals',
 '2025 12 Tourist nights',
 '2025 01.-12. Tourist arrivals',
 '2025 01.-12. Tourist nights']

In [51]:
# Toursimusdaten vom Wide Format ins Long Format umformen
df_tourism_germany_long = df_tourism_germany.melt(
    id_vars=["Spatial unit", "Countries"],
    var_name="Zeitraum_Kennzahl",
    value_name="Wert"
)

df_tourism_germany_long.head()

       Spatial unit Countries         Zeitraum_Kennzahl   Wert
0  County of Istria   Germany  2019 01 Tourist arrivals    478
1  County of Istria   Germany    2019 01 Tourist nights   5512
2  County of Istria   Germany  2019 02 Tourist arrivals   1445
3  County of Istria   Germany    2019 02 Tourist nights   4951
4  County of Istria   Germany  2019 03 Tourist arrivals  10138

In [52]:
df_tourism_germany_long.shape

(182, 4)

In [53]:
# Jahr aus der Spalte Zeitraum_Kennzahl extrahieren
df_tourism_germany_long["Jahr"] = (
    df_tourism_germany_long["Zeitraum_Kennzahl"].str[:4]
)

df_tourism_germany_long.head()

       Spatial unit Countries         Zeitraum_Kennzahl   Wert  Jahr
0  County of Istria   Germany  2019 01 Tourist arrivals    478  2019
1  County of Istria   Germany    2019 01 Tourist nights   5512  2019
2  County of Istria   Germany  2019 02 Tourist arrivals   1445  2019
3  County of Istria   Germany    2019 02 Tourist nights   4951  2019
4  County of Istria   Germany  2019 03 Tourist arrivals  10138  2019

In [54]:
# Monat aus der Spalte Zeitraum_Kennzahl extrahieren 
df_tourism_germany_long["Monat"] = (
    df_tourism_germany_long["Zeitraum_Kennzahl"].str[5:7]
)

df_tourism_germany_long.head()

       Spatial unit Countries         Zeitraum_Kennzahl   Wert  Jahr Monat
0  County of Istria   Germany  2019 01 Tourist arrivals    478  2019    01
1  County of Istria   Germany    2019 01 Tourist nights   5512  2019    01
2  County of Istria   Germany  2019 02 Tourist arrivals   1445  2019    02
3  County of Istria   Germany    2019 02 Tourist nights   4951  2019    02
4  County of Istria   Germany  2019 03 Tourist arrivals  10138  2019    03

In [55]:
# Kennzahl aus der Spalte Zeitraum_Kennzahl extrahieren 
df_tourism_germany_long["Kennzahl"] = (
    df_tourism_germany_long["Zeitraum_Kennzahl"].str.extract(r"(Tourist arrivals|Tourist nights)")
)

df_tourism_germany_long.head()

,Spatial unit,Countries,Zeitraum_Kennzahl,Wert,Jahr,Monat,Kennzahl
0,County of Istria,Germany,2019 01 Tourist arrivals,478,2019,01,Tourist arrivals
1,County of Istria,Germany,2019 01 Tourist nights,5512,2019,01,Tourist nights
2,County of Istria,Germany,2019 02 Tourist arrivals,1445,2019,02,Tourist arrivals
3,County of Istria,Germany,2019 02 Tourist nights,4951,2019,02,Tourist nights
4,County of Istria,Germany,2019 03 Tourist arrivals,10138,2019,03,Tourist arrivals

In [56]:
# Jahressumme im Datensatz prüfen
df_tourism_germany_long.loc[
    df_tourism_germany_long["Zeitraum_Kennzahl"].str.contains("01.-12.", regex=False)
]

,Spatial unit,Countries,Zeitraum_Kennzahl,Wert,Jahr,Monat,Kennzahl
24,County of Istria,Germany,2019 01.-12. Tourist arrivals,1051643,2019,01,Tourist arrivals
25,County of Istria,Germany,2019 01.-12. Tourist nights,8580194,2019,01,Tourist nights
50,County of Istria,Germany,2020 01.-12. Tourist arrivals,594375,2020,01,Tourist arrivals
51,County of Istria,Germany,2020 01.-12. Tourist nights,5116483,2020,01,Tourist nights
76,County of Istria,Germany,2021 01.-12. Tourist arrivals,1145072,2021,01,Tourist arrivals
77,County of Istria,Germany,2021 01.-12. Tourist nights,9332509,2021,01,Tourist nights
102,County of Istria,Germany,2022 01.-12. Tourist arrivals,1309379,2022,01,Tourist arrivals
103,County of Istria,Germany,2022 01.-12. Tourist nights,10871010,2022,01,Tourist nights
128,County of Istria,Germany,2023 01.-12. Tourist arrivals,1285731,2023,01,Tourist arrivals
129,County of Istria,Germany,2023 01.-12. Tourist nights,10459665,2023,01,Tourist nights
154,County of Istria,Germany,2024 01.-12. Tourist arrivals,1231169,2024,01,Tourist arrivals
155,County of Istria,Germany,2024 01.-12. Tourist nights,9916343,2024,01,Tourist nights
180,County of Istria,Germany,2025 01.-12. Tourist arrivals,1233549,2025,01,Tourist arrivals
181,County of Istria,Germany,2025 01.-12. Tourist nights,9962630,2025,01,Tourist nights

In [57]:
# Jahressummen in der Spalte Monat kennzeichnen
df_tourism_germany_long.loc[
    df_tourism_germany_long["Zeitraum_Kennzahl"].str.contains("01.-12.", regex=False),
    "Monat"
] = "Gesamt"

df_tourism_germany_long.tail()

,Spatial unit,Countries,Zeitraum_Kennzahl,Wert,Jahr,Monat,Kennzahl
177,County of Istria,Germany,2025 11 Tourist nights,18229,2025,11,Tourist nights
178,County of Istria,Germany,2025 12 Tourist arrivals,5017,2025,12,Tourist arrivals
179,County of Istria,Germany,2025 12 Tourist nights,22210,2025,12,Tourist nights
180,County of Istria,Germany,2025 01.-12. Tourist arrivals,1233549,2025,Gesamt,Tourist arrivals
181,County of Istria,Germany,2025 01.-12. Tourist nights,9962630,2025,Gesamt,Tourist nights

In [58]:
# Kennzeichnung der Jahressumen prüfen 
df_tourism_germany_long["Monat"].value_counts()

Monat
01        14
02        14
03        14
04        14
05        14
06        14
07        14
08        14
09        14
10        14
11        14
12        14
Gesamt    14
Name: count, dtype: int64

In [59]:
# Kennzahlen in separate Spalte umformen 
df_tourism_germany_clean = df_tourism_germany_long.pivot(
    index=["Spatial unit", "Countries", "Jahr", "Monat"],
    columns="Kennzahl",
    values="Wert"
).reset_index()

df_tourism_germany_clean.head()

Kennzahl,Spatial unit,Countries,Jahr,Monat,Tourist arrivals,Tourist nights
0,County of Istria,Germany,2019,01,478,5512
1,County of Istria,Germany,2019,02,1445,4951
2,County of Istria,Germany,2019,03,10138,40996
3,County of Istria,Germany,2019,04,44181,214843
4,County of Istria,Germany,2019,05,65858,396073

In [60]:
# Namen der Spaltenachse entfernen
df_tourism_germany_clean.columns.name = None

df_tourism_germany_clean.head()

       Spatial unit Countries  Jahr Monat  Tourist arrivals  Tourist nights
0  County of Istria   Germany  2019    01               478            5512
1  County of Istria   Germany  2019    02              1445            4951
2  County of Istria   Germany  2019    03             10138           40996
3  County of Istria   Germany  2019    04             44181          214843
4  County of Istria   Germany  2019    05             65858          396073

In [61]:
# Struktur der bereinigten Datensatzes prüfen 
df_tourism_germany_clean.shape

(91, 6)

In [62]:
df_tourism_germany_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Spatial unit      91 non-null     str
 1   Countries         91 non-null     str
 2   Jahr              91 non-null     str
 3   Monat             91 non-null     str
 4   Tourist arrivals  91 non-null     int64
 5   Tourist nights    91 non-null     int64
dtypes: int64(2), str(4)
memory usage: 4.4 KB

In [63]:
# Datentype der Spalte Jahr anpassen
df_tourism_germany_clean["Jahr"] = (
    df_tourism_germany_clean["Jahr"].astype("int64")
)

df_tourism_germany_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Spatial unit      91 non-null     str
 1   Countries         91 non-null     str
 2   Jahr              91 non-null     int64
 3   Monat             91 non-null     str
 4   Tourist arrivals  91 non-null     int64
 5   Tourist nights    91 non-null     int64
dtypes: int64(3), str(3)
memory usage: 4.4 KB

In [64]:
# Fehlende Werte erneut im bereinigten Datensatz prüfen 
df_tourism_germany_clean.isna().sum()

Spatial unit        0
Countries           0
Jahr                0
Monat               0
Tourist arrivals    0
Tourist nights      0
dtype: int64

In [65]:
# Bereinigte Tourismusdaten Deutschland - Istrien speichern 
df_tourism_germany_clean.to_csv(
    "data/processed/tourism_germany_istria_clean.csv",
    index=False
)

In [66]:
# Tourismusdaten der istrischen Städte und Gemeinden einlesen 
df_tourism_jls = pd.read_csv(
    "data/raw/tourism_istria_jls_2020_2025.csv"
)

df_tourism_jls.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Table 1.8. Accommodation capacities, tourist arrivals and nights, Republic of Croatia, HR_NUTS 2021 - HR NUTS 2, counties, towns and municipalities, by months
Spatial unit    2020 01 Tourist arrivals - total 2020 01 Tourist nights - total 2020 02 Tourist arrivals - total 2020 02 Tourist nights - total 2020 03 Tourist arrivals - total 2020 03 Tourist nights - total 2020 04 Tourist arrivals - total 2020 04 Tourist nights - total 2020 05 Tourist arrivals - total 2020 05 Tourist nights - total 2020 06 Tourist arrivals - total 2020 06 Tourist nights - total 2020 07 Tourist arrivals - total 2020 07 Tourist nights - total 2020 08 Tourist arrivals - total 2020 08 Tourist nights - total 2020 09 Tourist arrivals - total 2020 09 Tourist nights - total 2020 10 Tourist arrivals - total 2020 10 Tourist nights - total 2020 11 Tourist arrivals - total 2020 11 Tourist nights - total 2020 12 Tourist arrivals - total 2020 12 Tourist nights - total 2020 01.-12. Tourist arrivals - total 2020 01.-12. Tourist nights - total 2021 01 Tourist arrivals - total 2021 01 Tourist nights - total 2021 02 Tourist arrivals - total 2021 02 Tourist nights - total 2021 03 Tourist arrivals - total 2021 03 Tourist nights - total 2021 04 Tourist arrivals - total 2021 04 Tourist nights - total 2021 05 Tourist arrivals - total 2021 05 Tourist nights - total 2021 06 Tourist arrivals - total 2021 06 Tourist nights - total 2021 07 Tourist arrivals - total 2021 07 Tourist nights - total 2021 08 Tourist arrivals - total 2021 08 Tourist nights - total 2021 09 Tourist arrivals - total 2021 09 Tourist nights - total 2021 10 Tourist arrivals - total 2021 10 Tourist nights - total 2021 11 Tourist arrivals - total 2021 11 Tourist nights - total 2021 12 Tourist arrivals - total 2021 12 Tourist nights - total 2021 01.-12. Tourist arrivals - total 2021 01.-12. Tourist nights - total 2022 01 Tourist arrivals - total 2022 01 Tourist nights - total 2022 02 Tourist arrivals - total 2022 02 Tourist nights - total 2022 03 Tourist arrivals - total 2022 03 Tourist nights - total 2022 04 Tourist arrivals - total 2022 04 Tourist nights - total 2022 05 Tourist arrivals - total 2022 05 Tourist nights - total 2022 06 Tourist arrivals - total 2022 06 Tourist nights - total 2022 07 Tourist arrivals - total 2022 07 Tourist nights - total 2022 08 Tourist arrivals - total 2022 08 Tourist nights - total 2022 09 Tourist arrivals - total 2022 09 Tourist nights - total 2022 10 Tourist arrivals - total 2022 10 Tourist nights - total 2022 11 Tourist arrivals - total 2022 11 Tourist nights - total 2022 12 Tourist arrivals - total 2022 12 Tourist nights - total 2022 01.-12. Tourist arrivals - total 2022 01.-12. Tourist nights - total 2023 01 Tourist arrivals - total 2023 01 Tourist nights - total 2023 02 Tourist arrivals - total 2023 02 Tourist nights - total 2023 03 Tourist arrivals - total 2023 03 Tourist nights - total 2023 04 Tourist arrivals - total 2023 04 Tourist nights - total 2023 05 Tourist arrivals - total 2023 05 Tourist nights - total 2023 06 Tourist arrivals - total 2023 06 Tourist nights - total 2023 07 Tourist arrivals - total 2023 07 Tourist nights - total 2023 08 Tourist arrivals - total 2023 08 Tourist nights - total 2023 09 Tourist arrivals - total 2023 09 Tourist nights - total 2023 10 Tourist arrivals - total 2023 10 Tourist nights - total 2023 11 Tourist arrivals - total 2023 11 Tourist nights - total 2023 12 Tourist arrivals - total 2023 12 Tourist nights - total 2023 01.-12. Tourist arrivals - total 2023 01.-12. Tourist nights - total 2024 01 Tourist arrivals - total 2024 01 Tourist nights - total 2024 02 Tourist arrivals - total 2024 02 Tourist nights - total 2024 03 Tourist arrivals - total 2024 03 Tourist nights - total 2024 04 Tourist arrivals - total 2024 04 Tourist nights - total 2024 05 Tourist arrivals - total 2024 05 Tourist nights - total 2024 06 Tourist arrivals - total 2024 06 Tourist nights - total 2024 07 Tourist arrivals - total 2024 07 Tourist nights - total 2024 08 Tourist arrivals - total 2024 08 Tourist nights - total 2024 09 Tourist arrivals - total 2024 09 Tourist nights - total 2024 10 Tourist arrivals - total 2024 10 Tourist nights - total 2024 11 Tourist arrivals - total 2024 11 Tourist nights - total 2024 12 Tourist arrivals - total 2024 12 Tourist nights - total 2024 01.-12. Tourist arrivals - total 2024 01.-12. Tourist nights - total 2025 01 Tourist arrivals - total 2025 01 Tourist nights - total 2025 02 Tourist arrivals - total 2025 02 Tourist nights - total 2025 03 Tourist arrivals - total 2025 03 Tourist nights - total 2025 04 Tourist arrivals - total 2025 04 Tourist nights - total 2025 05 Tourist arrivals - total 2025 05 Tourist nights - total 2025 06 Tourist arrivals - total 2025 06 Tourist nights - total 2025 07 Tourist arrivals - total 2025 07 Tourist nights - total 2025 08 Tourist arrivals - total 2025 08 Tourist nights - total 2025 09 Tourist arrivals - total 2025 09 Tourist nights - total 2025 10 Tourist arrivals - total 2025 10 Tourist nights - total 2025 11 Tourist arrivals - total 2025 11 Tourist nights - total 2025 12 Tourist arrivals - total 2025 12 Tourist nights - total 2025 01.-12. Tourist arrivals - total                2025 01.-12. Tourist nights - total
Novigrad        z                                z                              z                                z                              14                               36                             -                                -                              z                                z                              325                              1906                           1495                             11960                          1829                             14779                          92                               1354                           4                                102                            -                                -                              z                                z                              3774                                  30225                               -                                -                              z                                z                              6                                96                             40                               192                            72                               394                            527                              3225                           2091                             15033                          2529                             21034                          714                              6127                           89                               743                            z                                z                              8                                88                             6082                                  47067                               1                                32                             z                                z                              z                                z                              201                              916                            409                              2331                           1158                             7906                           2837                             19862                          2598                             22225                          767                              6477                           80                               519                            0                                162                            -                                -                              8056                                  60469                               7                                120                            21                               127                            20                               140                            130                              472                            473                              2876                           1009                             8074                           3145                             20635                          2576                             21121                          611                              5979                           76                               660                            6                                69                             4                                36                             8078                                  60309                               z                                z                              z                                z                              21                               193                            99                               458                            501                              3050                           984                              6520                           2576                             17882                          2827                             19280                          548                              5252                           80                               671                            1                                20                             z                                z                              7650                                  53375                               15                               44                             z                                z                              8                                174                            86                               427                            322                              1486                           1227                             7298                           2672                             17481                          2926                             20219                          636                              5301                           z                                z                              5                                20                             11                               103                            8018                                                                               53348

In [67]:
# Anzahl Zeilen und Spalten 
df_tourism_jls.shape

(7, 1)

In [68]:
df_tourism_jls.columns

Index(['Table 1.8. Accommodation capacities, tourist arrivals and nights, Republic of Croatia, HR_NUTS 2021 - HR NUTS 2, counties, towns and municipalities, by months'], dtype='str')

In [69]:
# Tourismusdaten der istrischen Städte und Gemeinden korrekt einlesen 
df_tourism_jls = pd.read_csv(
    "data/raw/tourism_istria_jls_2020_2025.csv",
    skiprows=2
)

df_tourism_jls.head()

,Spatial unit,2020 01 Tourist arrivals - total,2020 01 Tourist nights - total,2020 02 Tourist arrivals - total,2020 02 Tourist nights - total,2020 03 Tourist arrivals - total,2020 03 Tourist nights - total,2020 04 Tourist arrivals - total,2020 04 Tourist nights - total,2020 05 Tourist arrivals - total,...,2025 09 Tourist arrivals - total,2025 09 Tourist nights - total,2025 10 Tourist arrivals - total,2025 10 Tourist nights - total,2025 11 Tourist arrivals - total,2025 11 Tourist nights - total,2025 12 Tourist arrivals - total,2025 12 Tourist nights - total,2025 01.-12. Tourist arrivals - total,2025 01.-12. Tourist nights - total
0,Novigrad,z,z,z,z,14,36,-,-,z,...,636,5301,z,z,5,20,11,103,8018,53348
1,Medulin,1400,6425,4040,14549,1745,5207,2,46,1800,...,45355,305318,6809,34365,z,z,z,z,446639,2627303
2,Pore - Parenzo,3781,15399,8349,26351,2663,11939,10,303,672,...,74627,445450,37068,139438,10002,25126,13285,33951,643903,3288169
3,Pula - Pola,2364,7254,3259,9169,1112,4228,43,904,1303,...,49925,229180,21517,65773,7452,17861,8636,20842,462949,2014954
4,Rovinj - Rovigno,11510,31624,13663,36970,3834,10880,18,354,2106,...,93323,608414,36726,128177,14796,40550,14367,38406,759719,4226580

In [70]:
# Datentypen und Struktur des Datensatzes prüfen 
df_tourism_jls.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 157 entries, Spatial unit to 2025 01.-12. Tourist nights - total
dtypes: int64(112), str(45)
memory usage: 7.5 KB

In [71]:
# Enthaltene Städte und Gemeinde prüfen 
df_tourism_jls["Spatial unit"].unique()

<StringArray>
[        'Novigrad',          'Medulin',  'Pore  - Parenzo',
      'Pula - Pola', 'Rovinj - Rovigno',      'Umag -Umago']
Length: 6, dtype: str

In [72]:
# Sonderwerte im Datensatz prüfen 
# Laut Kroatischen Statiskamt exsistiert möglicherweise der Wert, aber aus Datenschutz/Vetraulichkeitsgründen wird nicht veröffentlicht
(df_tourism_jls == "z").sum().sum()

np.int64(46)

In [73]:
# Bindestriche im Datensatz prüfen 
# DZS Symboldefinition ist eindeutig "no occuurence" - nicht aufgetreten
(df_tourism_jls == "-").sum().sum()

np.int64(8)

In [74]:
# Sonderwerte bereinigen 
df_tourism_jls = df_tourism_jls.replace({
    "z": pd.NA,
    "-": 0
})

In [75]:
# Datentypen nach der Bereinigung prüfen 
df_tourism_jls.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 157 entries, Spatial unit to 2025 01.-12. Tourist nights - total
dtypes: int64(112), object(8), str(37)
memory usage: 7.5+ KB

In [76]:
# Spalten mit den Tourismuswerten auswählen 
tourism_columns = df_tourism_jls.columns[1:]

#Tourismuswerte in numerische Datentypen umwandeln 
for col in tourism_columns:
    df_tourism_jls[col] = df_tourism_jls[col].astype("Float64")

In [77]:
# Datentypen nach der Umwandlung prüfen
df_tourism_jls.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 157 entries, Spatial unit to 2025 01.-12. Tourist nights - total
dtypes: Float64(156), str(1)
memory usage: 8.4 KB

In [78]:
# Tourismusdaten vom Wide Format ins Long Format umformen 
df_tourism_jls_long = df_tourism_jls.melt(
    id_vars=["Spatial unit"],
    var_name="Zeitraum_Kennzahl",
    value_name="Wert"
)

df_tourism_jls_long.head()

       Spatial unit                 Zeitraum_Kennzahl     Wert
0          Novigrad  2020 01 Tourist arrivals - total     <NA>
1           Medulin  2020 01 Tourist arrivals - total   1400.0
2   Pore  - Parenzo  2020 01 Tourist arrivals - total   3781.0
3       Pula - Pola  2020 01 Tourist arrivals - total   2364.0
4  Rovinj - Rovigno  2020 01 Tourist arrivals - total  11510.0

In [79]:
df_tourism_jls_long.shape

(936, 3)

In [80]:
# Jahr aus der Spalte Zeitraum_Kennzahl extrahieren 
df_tourism_jls_long["Jahr"] = (
    df_tourism_jls_long["Zeitraum_Kennzahl"].str[:4]
)

df_tourism_jls_long.head()

       Spatial unit                 Zeitraum_Kennzahl     Wert  Jahr
0          Novigrad  2020 01 Tourist arrivals - total     <NA>  2020
1           Medulin  2020 01 Tourist arrivals - total   1400.0  2020
2   Pore  - Parenzo  2020 01 Tourist arrivals - total   3781.0  2020
3       Pula - Pola  2020 01 Tourist arrivals - total   2364.0  2020
4  Rovinj - Rovigno  2020 01 Tourist arrivals - total  11510.0  2020

In [81]:
# Monat aus der Spalte Zeitraum_Kennzahl extrahieren 
df_tourism_jls_long["Monat"] = (
    df_tourism_jls_long["Zeitraum_Kennzahl"].str[5:7]
)

df_tourism_jls_long.head()

       Spatial unit                 Zeitraum_Kennzahl     Wert  Jahr Monat
0          Novigrad  2020 01 Tourist arrivals - total     <NA>  2020    01
1           Medulin  2020 01 Tourist arrivals - total   1400.0  2020    01
2   Pore  - Parenzo  2020 01 Tourist arrivals - total   3781.0  2020    01
3       Pula - Pola  2020 01 Tourist arrivals - total   2364.0  2020    01
4  Rovinj - Rovigno  2020 01 Tourist arrivals - total  11510.0  2020    01

In [82]:
# Jahressumme in der Spalte Monat kennzeichnen
df_tourism_jls_long.loc[
    df_tourism_jls_long["Zeitraum_Kennzahl"].str.contains("01.-12.", regex=False),
    "Monat"
] = "Gesamt"

In [83]:
df_tourism_jls_long["Monat"].value_counts()

Monat
01        72
02        72
03        72
04        72
05        72
06        72
07        72
08        72
09        72
10        72
11        72
12        72
Gesamt    72
Name: count, dtype: int64

In [84]:
# Kennzahl aus der Spalte Zeitraum_Kennzahl extrahieren 
df_tourism_jls_long["Kennzahl"] = (
    df_tourism_jls_long["Zeitraum_Kennzahl"]
    .str.extract(r"(Tourist arrivals|Tourist nights)")
)

In [85]:
df_tourism_jls_long["Kennzahl"].value_counts()

Kennzahl
Tourist arrivals    468
Tourist nights      468
Name: count, dtype: int64

In [86]:
# Kennzahl in separate Spalte umformen 
df_tourism_jls_clean = df_tourism_jls_long.pivot(
    index=["Spatial unit", "Jahr", "Monat"],
    columns="Kennzahl",
    values="Wert"
).reset_index()

df_tourism_jls_clean.head()

Kennzahl Spatial unit  Jahr Monat  Tourist arrivals  Tourist nights
0             Medulin  2020    01            1400.0          6425.0
1             Medulin  2020    02            4040.0         14549.0
2             Medulin  2020    03            1745.0          5207.0
3             Medulin  2020    04               2.0            46.0
4             Medulin  2020    05            1800.0          4779.0

In [87]:
df_tourism_jls_clean.shape

(468, 5)

In [88]:
# Name der Spaltenachse entfernen
df_tourism_jls_clean.columns.name = None

In [89]:
# Bereinigte Datensätze prüfen 
df_tourism_jls_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Spatial unit      468 non-null    str
 1   Jahr              468 non-null    str
 2   Monat             468 non-null    str
 3   Tourist arrivals  445 non-null    Float64
 4   Tourist nights    445 non-null    Float64
dtypes: Float64(2), str(3)
memory usage: 19.3 KB

In [90]:
# Datentypen der Spalte Jahr anpassen
df_tourism_jls_clean["Jahr"] = (
    df_tourism_jls_clean["Jahr"].astype("int64")
)

In [91]:
# Fehlende Werte prüfen 
df_tourism_jls_clean.isna().sum()

Spatial unit         0
Jahr                 0
Monat                0
Tourist arrivals    23
Tourist nights      23
dtype: int64

In [92]:
# Duplikate prüfen 
df_tourism_jls_clean.duplicated().sum()

np.int64(0)

In [93]:
# Bereinigte Tourismusdaten der istrischen Städte und Gemeinden speichern 
df_tourism_jls_clean.to_csv(
    "data/processed/tourism_istria_jls_clean.csv",
    index=False
)

In [94]:
# Immobilienpreisdaten einlesen 
df_prices = pd.read_excel(
    "data/raw/real_estate_prices_2012_2025.xlsx",
    sheet_name="Stanovi_apartmani EUR"
)

df_prices.head()

,Šifra,Naziv županije,Naziv JLS-a,Tip JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.,"""."" označava da nema transakcija"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""z"" označava da ima manje od 10 transakcija pa..."
1,19.0,Vukovarsko-srijemska,ANDRIJAŠEVCI,Općina,z,.,.,.,.,.,.,.,z,.,.,.,z,.,NaN
2,27.0,Osječko-baranjska,ANTUNOVAC,Općina,z,.,.,.,.,.,.,z,z,z,z,.,.,.,NaN
3,35.0,Vukovarsko-srijemska,BABINA GREDA,Općina,.,.,.,.,.,.,.,.,.,.,z,.,.,.,NaN
4,43.0,Primorsko-goranska,BAKAR,Grad,z,z,667.880819,z,z,z,751.446151,547.865209,979.514324,948.976124,z,1108,1542.27002,2073.72998,NaN

In [95]:
# Leere erste Zeilen entfernen
df_prices = df_prices.dropna(how="all").reset_index(drop=True)

df_prices.shape

(557, 19)

In [96]:
# Struktur des Preisdatensatzes prüfen
df_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Šifra                             556 non-null    float64
 1   Naziv županije                    556 non-null    str
 2   Naziv JLS-a                       556 non-null    str
 3   Tip JLS-a                         556 non-null    str
 4   2012.                             556 non-null    object
 5   2013.                             556 non-null    object
 6   2014.                             556 non-null    object
 7   2015.                             556 non-null    object
 8   2016.                             556 non-null    object
 9   2017.                             556 non-null    object
 10  2018.                             556 non-null    object
 11  2019.                             556 non-null    object
 12  2020.                             556 non-null    object
 13  2021.                             556 non-null    object
 14  2022.                             556 non-null    object
 15  2023.                             556 non-null    object
 16  2024.                             556 non-null    object
 17  2025.                             556 non-null    object
 18  "." označava da nema transakcija  1 non-null      str
dtypes: float64(1), object(14), str(4)
memory usage: 82.8+ KB

In [97]:
# Letzte Spalte mit der Fußnote entferne
df_prices = df_prices.iloc[:, :-1]

#Leere Zeilen entfernen und Index zurücksetzen 
df_prices = df_prices.dropna(how="all").reset_index(drop=True)

#Größe des Datensatzes prüfen 
df_prices.shape

(556, 18)

In [98]:
#Jahres Spalte auswählen
year_columns = [f"{year}." for year in range(2012, 2026)]

#Sonderwerte durch fehlende Werte ersetzten 
df_prices.loc[:, year_columns] = (
    df_prices.loc[:, year_columns]
    .replace({".": pd.NA, "z": pd.NA})
)

In [99]:
#Jahrespalten in nummerische Datentypen umwandeln
for col in year_columns:
    df_prices[col] = df_prices[col].astype("Float64")

In [100]:
df_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Šifra           556 non-null    float64
 1   Naziv županije  556 non-null    str
 2   Naziv JLS-a     556 non-null    str
 3   Tip JLS-a       556 non-null    str
 4   2012.           128 non-null    Float64
 5   2013.           119 non-null    Float64
 6   2014.           124 non-null    Float64
 7   2015.           121 non-null    Float64
 8   2016.           143 non-null    Float64
 9   2017.           143 non-null    Float64
 10  2018.           156 non-null    Float64
 11  2019.           179 non-null    Float64
 12  2020.           169 non-null    Float64
 13  2021.           170 non-null    Float64
 14  2022.           192 non-null    Float64
 15  2023.           173 non-null    Float64
 16  2024.           163 non-null    Float64
 17  2025.           146 non-null    Float64
dtypes: Float64(14), float64(1), str(3)
memory usage: 85.9 KB

In [101]:
#Immobilienpreise auf Istrien filtern 
df_prices_istria = df_prices.loc[
    df_prices["Naziv županije"] == "Istarska"
]

df_prices_istria.shape

(41, 18)

In [102]:
# Immobilienpreise für 2025 prüfen 
df_prices_istria[
    ["Naziv JLS-a", "2025."]
].dropna()

                    Naziv JLS-a        2025.
44                  BUJE - BUIE  2119.389893
224                       LABIN  2688.030029
236         LIŽNJAN - LISIGNANO  2424.449951
268                     MEDULIN   2273.02002
327                       PAZIN  2182.264893
357             POREČ - PARENZO  2774.419922
375                 PULA - POLA  2456.219971
384                        RAŠA  2039.030029
391            ROVINJ - ROVIGNO  3354.735107
443               SVETA NEDELJA  2413.379883
468  TAR-VABRIGA - TORRE-ABREGA  2831.379883
487                UMAG - UMAGO  3551.129883
520           VODNJAN - DIGNANO  2331.725098
533              VRSAR - ORSERA  2832.219971
552                       ŽMINJ  2576.330078

In [103]:
# Korrikierte Immobilienpreise für Istrien speichern 
df_prices_istria.to_csv(
    "data/processed/real_estate_prices_istria_clean.csv",
    index=False
)

In [104]:
# Check Immobilienpreisdaten
df_prices_check = pd.read_csv(
    "data/processed/real_estate_prices_istria_clean.csv"
)

df_prices_check[["Naziv JLS-a", "2025."]].dropna()

                   Naziv JLS-a        2025.
3                  BUJE - BUIE  2119.389893
14                       LABIN  2688.030029
16         LIŽNJAN - LISIGNANO  2424.449951
19                     MEDULIN  2273.020020
23                       PAZIN  2182.264893
25             POREČ - PARENZO  2774.419922
26                 PULA - POLA  2456.219971
27                        RAŠA  2039.030029
28            ROVINJ - ROVIGNO  3354.735107
29               SVETA NEDELJA  2413.379883
33  TAR-VABRIGA - TORRE-ABREGA  2831.379883
35                UMAG - UMAGO  3551.129883
38           VODNJAN - DIGNANO  2331.725098
39              VRSAR - ORSERA  2832.219971
40                       ŽMINJ  2576.330078

In [105]:
import numpy as np
import pandas as pd

In [106]:
import numpy as np
import pandas as pd

In [107]:
# Immobilienpreise für Familienhäuser einlesen
df_house_prices = pd.read_excel(
    "data/raw/real_estate_prices_2012_2025.xlsx",
    sheet_name="Obiteljske kuće_ EUR"
)

df_house_prices.head()

,Šifra,Naziv županije,Naziv JLS-a,Tip JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.,"""."" označava da nema transakcija"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""z"" označava da ima manje od 10 transakcija pa..."
1,19.0,Vukovarsko-srijemska,ANDRIJAŠEVCI,Općina,z,z,.,z,.,.,17.424206,17.831689,z,z,z,z,z,z,NaN
2,27.0,Osječko-baranjska,ANTUNOVAC,Općina,z,146.748921,z,z,z,z,24.545086,24.498066,23.794384,49.114965,121.022625,285,327,468,NaN
3,35.0,Vukovarsko-srijemska,BABINA GREDA,Općina,z,z,z,.,.,.,16.494223,17.711452,z,z,z,z,z,.,NaN
4,43.0,Primorsko-goranska,BAKAR,Grad,323.330762,z,z,206.408983,z,146.403541,97.9315,173.460816,112.793173,130.317143,213.971736,186,338,180,NaN

In [108]:
df_house_prices.shape

(557, 19)

In [109]:
df_house_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Šifra                             556 non-null    float64
 1   Naziv županije                    556 non-null    str
 2   Naziv JLS-a                       556 non-null    str
 3   Tip JLS-a                         556 non-null    str
 4   2012.                             556 non-null    object
 5   2013.                             556 non-null    object
 6   2014.                             556 non-null    object
 7   2015.                             556 non-null    object
 8   2016.                             556 non-null    object
 9   2017.                             556 non-null    object
 10  2018.                             556 non-null    object
 11  2019.                             556 non-null    object
 12  2020.                             556 non-null    object
 13  2021.                             556 non-null    object
 14  2022.                             556 non-null    object
 15  2023.                             556 non-null    object
 16  2024.                             556 non-null    object
 17  2025.                             556 non-null    object
 18  "." označava da nema transakcija  1 non-null      str
dtypes: float64(1), object(14), str(4)
memory usage: 82.8+ KB

In [110]:
# Leere Zeile entferne
df_house_prices = df_house_prices.dropna(
    how="all"
)

#Letze Spalte mit der Erklärung entfernen
df_house_prices = df_house_prices.iloc[:, :-1]

df_house_prices.shape

(557, 18)

In [111]:
df_house_prices.head()

,Šifra,Naziv županije,Naziv JLS-a,Tip JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19.0,Vukovarsko-srijemska,ANDRIJAŠEVCI,Općina,z,z,.,z,.,.,17.424206,17.831689,z,z,z,z,z,z
2,27.0,Osječko-baranjska,ANTUNOVAC,Općina,z,146.748921,z,z,z,z,24.545086,24.498066,23.794384,49.114965,121.022625,285,327,468
3,35.0,Vukovarsko-srijemska,BABINA GREDA,Općina,z,z,z,.,.,.,16.494223,17.711452,z,z,z,z,z,.
4,43.0,Primorsko-goranska,BAKAR,Grad,323.330762,z,z,206.408983,z,146.403541,97.9315,173.460816,112.793173,130.317143,213.971736,186,338,180

In [112]:
df_house_prices = df_house_prices.dropna(
    how="all"
)

df_house_prices.shape

(556, 18)

In [113]:
# Jahres Spalte auswählen
year_columns = [f"{year}." for year in range(2012, 2026)]

# Sonderwerte durch fehlende Werte ersetzen 
df_house_prices.loc[:, year_columns] = (
    df_house_prices.loc[:, year_columns]
    .replace({".": pd.NA, "z": pd.NA})
)

In [114]:
# Komma-Sonderwerte in Datensatz prüfen 
(df_house_prices[year_columns] == ",").sum().sum()

np.int64(58)

In [115]:
# Zeilen mit Komma-Sonderzeichen anzeigen 
df_house_prices[
    df_house_prices[year_columns].eq(",").any(axis=1)
]

,Šifra,Naziv županije,Naziv JLS-a,Tip JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.
11,116.0,Krapinsko-zagorska,BEDEKOVČINA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,20.905127,12.560832,29.70071,",",<NA>,<NA>
19,191.0,Varaždinska,BERETINEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
38,361.0,Varaždinska,BREZNICA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
39,1511.0,Varaždinska,BREZNIČKI HUM,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
44,418.0,Krapinsko-zagorska,BUDINŠČINA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
52,493.0,Karlovačka,CETINGRAD,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
53,507.0,Splitsko-dalmatinska,CISTA PROVO,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
54,515.0,Šibensko-kninska,CIVLJANE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
70,6033.0,Međimurska,DEKANOVEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
77,787.0,Međimurska,DONJA DUBRAVA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,23.132914,<NA>,<NA>,<NA>,25.803304,",",<NA>,<NA>
87,892.0,Međimurska,DONJI VIDOVEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
119,5711.0,Zadarska,GALOVAC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
125,1236.0,Međimurska,GORIČAN,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,17.410624,<NA>,18.794824,34.486559,19.780221,19.328423,<NA>,",",<NA>
131,1295.0,Varaždinska,GORNJI KNEGINEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33.621697,54.592196,24.168069,<NA>,<NA>,",",",",<NA>
139,1376.0,Vukovarsko-srijemska,GRADIŠTE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
147,1465.0,Krapinsko-zagorska,HRAŠĆINA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
170,5525.0,Krapinsko-zagorska,JESENJE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
171,1724.0,Karlovačka,JOSIPDOL,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,8.623209,6.772896,9.123973,11.76013,16.929412,9.595859,",",<NA>,<NA>
175,6238.0,Karlovačka,KAMANJE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
185,1830.0,Šibensko-kninska,KIJEVO,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
189,1872.0,Krapinsko-zagorska,KLANJEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,33.165395,<NA>,9.585094,<NA>,<NA>,",",<NA>
222,5533.0,Krapinsko-zagorska,KUMROVEC,Grad,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
236,2348.0,Zadarska,LIŠANE OSTROVIČKE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
240,5878.0,Splitsko-dalmatinska,LOKVIČIĆI,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
242,2399.0,Vukovarsko-srijemska,LOVAS,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
251,2470.0,Varaždinska,LJUBEŠĆICA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5.164343,<NA>,<NA>,<NA>,<NA>,",",<NA>
284,6122.0,Vukovarsko-srijemska,NEGOSLAVCI,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
294,5541.0,Krapinsko-zagorska,NOVI GOLUBOVEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
300,5614.0,Koprivničko-križevačka,NOVO VIRJE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
332,3263.0,Varaždinska,PETRIJANEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,13.449353,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
354,3441.0,Zadarska,POLAČA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,190.22098,",",<NA>,<NA>
367,5894.0,Splitsko-dalmatinska,PRGOMET,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
368,6203.0,Međimurska,PRIBISLAVEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,50.616466,<NA>,<NA>,70.020573,",",<NA>,<NA>
369,5908.0,Splitsko-dalmatinska,PRIMORSKI DOLAC,Općina,<NA>,728.047145,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
389,5568.0,Karlovačka,RIBNIK,Općina,472.541927,542.533037,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
395,5916.0,Splitsko-dalmatinska,RUNOVIĆI,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
397,3786.0,Karlovačka,SABORSKO,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
424,4103.0,Varaždinska,SRAČINEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.174452,<NA>,<NA>,<NA>,",",<NA>,<NA>
425,4111.0,Zadarska,STANKOVCI,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
436,5517.0,Zagrebačka,STUPNIK,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,135.605987,20.088729,69.946462,72.492535,",",<NA>,<NA>
443,6076.0,Međimurska,SVETA MARIJA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,24.644633,<NA>,31.976243,<NA>,",",<NA>
476,5576.0,Karlovačka,TOUNJ,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>,<NA>
502,4812.0,Krapinsko-zagorska,VELIKO TRGOVIŠĆE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,36.398127,19.483179,96.153689,<NA>,",",<NA>
504,4847.0,Varaždinska,VIDOVEC,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,35.285415,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
506,4863.0,Varaždinska,VINICA,Općina,250.191087,116.685733,<NA>,<NA>,<NA>,<NA>,9.278253,25.885427,<NA>,<NA>,<NA>,<NA>,",",<NA>
513,4936.0,Varaždinska,VISOKO,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",<NA>
523,5037.0,Karlovačka,VOJNIĆ,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.499843,0.998868,10.813638,13.28317,1.049837,",",<NA>,21
541,5215.0,Krapinsko-zagorska,ZAGORSKA SELA,Općina,593.183882,461.298324,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
545,5231.0,Dubrovačko-neretvanska,ZAŽABLJE,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,",",",",<NA>
549,5274.0,Krapinsko-zagorska,ZLATAR BISTRICA,Općina,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18.676446,<NA>,<NA>,",",<NA>

In [116]:
# Anzahl der Komma-Sonderwerte pro Jahr prüfen
(df_house_prices[year_columns] == ",").sum()

2012.     0
2013.     0
2014.     0
2015.     0
2016.     0
2017.     0
2018.     0
2019.     0
2020.     0
2021.     0
2022.     0
2023.    24
2024.    34
2025.     0
dtype: int64

In [117]:
# Sonderwerte durch fehlende Werte ersetzen
df_house_prices.loc[:, year_columns] = (
    df_house_prices.loc[:, year_columns]
    .replace({
        ".": pd.NA,
        "z": pd.NA,
        ",": pd.NA
    })
)

In [118]:
#Jahrespalte in numerischen Datentypen umwandeln 
for col in year_columns:
    df_house_prices[col] = df_house_prices[col].astype("Float64")

df_house_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 556 entries, 1 to 556
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Šifra           556 non-null    float64
 1   Naziv županije  556 non-null    str
 2   Naziv JLS-a     556 non-null    str
 3   Tip JLS-a       556 non-null    str
 4   2012.           77 non-null     Float64
 5   2013.           69 non-null     Float64
 6   2014.           69 non-null     Float64
 7   2015.           73 non-null     Float64
 8   2016.           75 non-null     Float64
 9   2017.           176 non-null    Float64
 10  2018.           306 non-null    Float64
 11  2019.           340 non-null    Float64
 12  2020.           334 non-null    Float64
 13  2021.           352 non-null    Float64
 14  2022.           369 non-null    Float64
 15  2023.           310 non-null    Float64
 16  2024.           278 non-null    Float64
 17  2025.           240 non-null    Float64
dtypes: Float64(14), float64(1), str(3)
memory usage: 85.9 KB

In [119]:
# Daten aus Istrien filtern
df_house_prices_istria = df_house_prices.loc[
    df_house_prices["Naziv županije"] == "Istarska"
]

df_house_prices_istria.shape

(41, 18)

In [120]:
# Duplikate prüfen 
df_house_prices_istria.duplicated().sum()

np.int64(0)

In [121]:
#Verfügbare Famielienhauspreise für 2025 prüfen
df_house_prices_istria["2025."].notna().sum()

np.int64(24)

In [122]:
# Fehlende Familienhauspreise für 2025 prüfen
df_house_prices_istria["2025."].isna().sum()

np.int64(17)

In [123]:
# Verfügbare und fehlende Familienhauspreise 2025 zusammen
print("Verfügbare Werte:", df_house_prices_istria["2025."].notna().sum())
print("Fehlende Werte:", df_house_prices_istria["2025."].isna().sum())

Verfügbare Werte: 24
Fehlende Werte: 17

In [124]:
# Bereinigte Familienhauspreise speichern 
df_house_prices_istria.to_csv(
    "data/processed/real_estate_house_prices_clean.csv",
    index=False
)

In [125]:
# Transaktionsdaten für Familienhäuser einlesen
df_house_transactions = pd.read_excel(
    "data/raw/real_estate_transactions_2012_2025.xlsx",
    sheet_name="Obiteljske kuće"
)

df_house_transactions.head()

,Šifra,Naziv županije,Naziv JLS-a,2012.,2013.,2014.,2015.,2016.,2017.,2018.,2019.,2020.,2021.,2022.,2023.,2024.,2025.,"""z"" označava manje od 10 transakcija"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""."" označava da nema transakcija"
1,19.0,Vukovarsko-srijemska,ANDRIJAŠEVCI,.,.,.,z,.,.,12,12,z,z,z,z,z,z,NaN
2,27.0,Osječko-baranjska,ANTUNOVAC,z,10,z,z,z,z,10,19,14,37,22,25,23,11,NaN
3,35.0,Vukovarsko-srijemska,BABINA GREDA,z,z,z,.,.,.,12,11,z,z,z,z,z,.,NaN
4,43.0,Primorsko-goranska,BAKAR,18,z,z,16,z,16,34,23,32,53,51,31,39,25,NaN

In [126]:
df_house_transactions.shape

(557, 18)

In [127]:
df_house_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Šifra                                 556 non-null    float64
 1   Naziv županije                        556 non-null    str
 2   Naziv JLS-a                           556 non-null    str
 3   2012.                                 556 non-null    object
 4   2013.                                 556 non-null    object
 5   2014.                                 556 non-null    object
 6   2015.                                 556 non-null    object
 7   2016.                                 556 non-null    object
 8   2017.                                 556 non-null    object
 9   2018.                                 556 non-null    object
 10  2019.                                 556 non-null    object
 11  2020.                                 556 non-null    object
 12  2021.                                 556 non-null    object
 13  2022.                                 556 non-null    object
 14  2023.                                 556 non-null    object
 15  2024.                                 556 non-null    object
 16  2025.                                 556 non-null    object
 17  "z" označava manje od 10 transakcija  1 non-null      str
dtypes: float64(1), object(14), str(3)
memory usage: 78.5+ KB

In [128]:
# Letzte Spalte mit der Erklärung entfernen
df_house_transactions = df_house_transactions.iloc[:,:-1]

# Leere Zeile entfernen
df_house_transactions = df_house_transactions.dropna(
    how="all"
)

df_house_transactions.shape

(556, 17)

In [129]:
# Jahresspalten definieren
year_columns = [f"{year}." for year in range(2012, 2026)]

# Sonderwerte durch fehlende Werte ersetzen
df_house_transactions.loc[:, year_columns] = (
    df_house_transactions.loc[:, year_columns]
    .replace({
        ".": pd.NA,
        "z": pd.NA
    })
)

In [130]:
# Jahrespalten in numerischen Datentyp umwandeln 
for col in year_columns:
    df_house_transactions[col] = (
        df_house_transactions[col].astype("Float64")
    )

In [131]:
df_house_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 556 entries, 1 to 556
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Šifra           556 non-null    float64
 1   Naziv županije  556 non-null    str
 2   Naziv JLS-a     556 non-null    str
 3   2012.           78 non-null     Float64
 4   2013.           68 non-null     Float64
 5   2014.           69 non-null     Float64
 6   2015.           72 non-null     Float64
 7   2016.           75 non-null     Float64
 8   2017.           176 non-null    Float64
 9   2018.           306 non-null    Float64
 10  2019.           340 non-null    Float64
 11  2020.           334 non-null    Float64
 12  2021.           352 non-null    Float64
 13  2022.           369 non-null    Float64
 14  2023.           311 non-null    Float64
 15  2024.           278 non-null    Float64
 16  2025.           240 non-null    Float64
dtypes: Float64(14), float64(1), str(2)
memory usage: 81.6 KB

In [132]:
# Transaktionsdaten auf Istrien filtern 
df_house_transactions_istria = df_house_transactions.loc[
    df_house_transactions["Naziv županije"] == "Istarska"
]

df_house_transactions_istria.shape

(41, 17)

In [133]:
# Duplikate prüfen
df_house_transactions_istria.duplicated().sum()

np.int64(0)

In [134]:
#Verfügbare und fehlende Familienhaus-Transaktionen 2025 prüfen 
print(
    df_house_transactions_istria["2025."].notna().sum()
)

print(
    "Fehlende Werte:",
    df_house_transactions_istria["2025."].isna().sum()
)

24
Fehlende Werte: 17

In [135]:
# Bereinigte Familienhaus-Transaktionen speichern 
df_house_transactions_istria.to_csv(
    "data/processed/real_estate_house_transactions_istria_clean.csv",
    index=False
)